### ISSUE TITLE
Yo install issue

### ISSUE THREAD

**Issue by amolc** [loopbackio/loopback.io#4]
yo loopback

Error: Cannot find module 'ansi-styles'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/chalk/index.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:3

**Comment by raymondfeng** [comment]
Can you run `slc update` to make sure all the strongloop command line tools are up to date? Please use `slc version` to report back the versions too.
