### ISSUE TITLE
SyntaxError: C:\loopback-getting-started\server\middleware.json: Unexpected token / in JSON at position 884

### ISSUE THREAD

**Issue by wzup** [loopbackio/loopback.io#560]
[Here ](https://loopback.io/doc/en/lb3/Defining-middleware.html#middleware-configuration-properties)you write
> In addition to a literal string, route can be a path matching pattern, a regular expression, or an array including all these types.

This is wrong and it throws!

I'm setting a regex in an array, but your framework throws:
```
    "routes:before": {
        "./middleware/foo": {
            "enabled": false,
            "paths": [/^\/(?!css|js|img).+$/ig]  <== doesn't work
        }
    },
```

It throws:
```
module.js:590
    throw err;
    ^

SyntaxError: C:\loopback-getting-started\server\middleware.json: Unexpected token / in JSON at position 884
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\loopback-getting-started\node_modules\loopback-boot\lib\config-loader.js:130:28
    at Array.map (native)
    at loadConfigFiles (C:\loopback-getting-started\node_modules\loopback-boot\lib\config-loader.js:129:16)
    at loadNamed (C:\loopback-getting-started\node_modules\loopback-boot\lib\config-loader.js:81:17)
    at Object.ConfigLoader.loadMiddleware (C:\loopback-getting-started\node_modules\loopback-boot\lib\config-loader.js:52:10)
    at compile (C:\loopback-getting-started\node_modules\loopback-boot\lib\compiler.js:74:18)
    at bootLoopBackApp (C:\loopback-getting-started\node_modules\loopback-boot\index.js:153:22)
    at Object.<anonymous> (C:\loopback-getting-started\server\server.js:51:1)
    at Module._compile (module.js:570:32)
```

How to pass regex in an array in `middleware.json`?

**Comment by bschrammIBM** [comment]
Thank you for pointing out this error. We are taking a look at it now.

**Comment by wzup** [comment]
@bschrammIBM , a string also doesn't work

> SyntaxError: Invalid regular expression: /^^\/(?:?!css|js|img)\.+$\/?(?=\/|$)/: Nothing to repeat

```
"paths": ["^\/(?!css|js|img).+$"]
```

**Comment by wzup** [comment]
On SO too 
https://stackoverflow.com/questions/47660626/unexpected-token-in-json-how-to-include-a-regex-in-an-array-in-a-json

**Comment by dhmlau** [comment]
@b-admike , could you please take a look? thanks.

**Comment by bschrammIBM** [comment]
We are looking at this issue and will be in touch in a few days.

**Comment by lancedouglas1** [comment]
Does this require the "/" and "/g" added to be valid JSON?

`"paths": /[/^\/(?!css|js|img).+$/ig]/g`
or simply
`"paths": /^\/(?!css|js|img).+$/ig`
