### ISSUE TITLE
Getting "Invalid target model for scope" on logging in with User.js subclass

### ISSUE THREAD

**Issue by JuergenSimon** [loopbackio/loopback.io#687]
## Nature of the issue 

I have a model `Customer`, which inherits from `User` (built-in model). It uses a polymorphic relationship to share `AccessToken` with `User`. When simply starting loopback and running things normally, there is no problem. 

Now we have a test setup for integration tests, in which the following happens:
* A test data source is created
* The models are attached (using the `attach` method) to the test data source

As a result, the `accessTokens` relationship in `Customer` gives me the following error when ever accessed:

```
{
  "message": "Invalid target model for scope `Customer.prototype.accessTokens`.",
  "stack": "Error: Invalid target model for scope `Customer.prototype.accessTokens`.\n    at ScopeDefinition.targetModel (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/scope.js:46:11)\n    at User.get (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/scope.js:239:36)\n    at User.<anonymous> (<anonymous>:1:26)\n    at defineScope (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/scope.js:525:3)\n    at Function.hasMany (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/relation-definition.js:771:3)\n    at Function.hasMany (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/relations.js:82:29)\n    at /Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/datasource.js:591:28\n    at Array.forEach (<anonymous>)\n    at DataSource.defineRelations (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/datasource.js:564:28)\n    at DataSource.setupDataAccess (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/datasource.js:701:8)\n    at DataSource.attach (/Users/bar/Projects/foo/src/appics-backend-common/node_modules/loopback-datasource-juggler/lib/datasource.js:945:8)\n    at Function.ModelClass.attachTo (/Users/bar/Projects/foo/src/appics-backend/node_modules/loopback-datasource-juggler/lib/model-builder.js:374:16)\n    at app.models.forEach (/Users/bar/Projects/foo/src/appics-backend-common/lib/test-utils/test-db.js:71:15)\n    at Array.forEach (<anonymous>)\n    at PostgresTestDB.attach (/Users/bar/Projects/foo/src/appics-backend-common/lib/test-utils/test-db.js:69:18)\n    at testDb.create.then (/Users/bar/Projects/foo/src/appics-backend/tests/setup.js:61:20)"
}

```
## Expected behavior
* The `Customer.accessTokens` method behaves normally. Login is possible.

## Actual behavior
* The `Customer.login` method always fails with the above error.

**Comment by JuergenSimon** [comment]
Note: the following things made no difference whatsoever:
* Moving the polymorphic relationship definitions from model-config.json into the model.json files
* Removing one of two subclasses of 'user' we are using and turning the relationship into a 'normal' (aka non-polymorphic) one.
* It seems that as soon as we attach models to the test data source, the `accessTokens` relationship is screwed up.

**Comment by charlie-s** [comment]
How are you defining these relationships? (do you have sample code)
